# Generated by Django 4.0.4 on 2022-11-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0002_remove_parkinglot_customer_parkinglot_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='qr_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
