# Generated by Django 4.0.4 on 2022-11-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0006_slot_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='who',
        ),
    ]
