# Generated by Django 4.0.4 on 2022-11-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0007_remove_slot_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_lot.slot'),
        ),
    ]
