# Generated by Django 4.0.4 on 2022-11-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0008_remove_parkinglot_customer_customer_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
