# Generated by Django 4.0.4 on 2022-11-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0009_parkinglot_lat_parkinglot_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slot',
        ),
        migrations.AddField(
            model_name='slot',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_lot.customer'),
        ),
    ]
