# Generated by Django 4.0.4 on 2022-11-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0010_remove_customer_slot_slot_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_lot.customer'),
        ),
    ]
