# Generated by Django 4.0.4 on 2022-11-19 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0011_slot_timestamp_alter_slot_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='timestamp',
            new_name='end',
        ),
        migrations.AddField(
            model_name='slot',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
