# Generated by Django 4.0.4 on 2022-11-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot', '0012_rename_timestamp_slot_end_slot_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end',
            field=models.TimeField(),
        ),
    ]
